import {idPlusPlus} from "../logic/Counter";

const gameNameCutter = function (name){
    const limit = 20;
    if(name.length > limit) return name.substring(0,limit);
    return name;
}

const textColor = '#000000';
const svgWidth = 380;
const svgHeight = 55;
const gameList = [
    {
        id: idPlusPlus(),
        title: 'Metal Slug',
        platform: 'Arcade',
        tag: 'metal',
        src: 'https://www.retrogames.cc/embed/9157-metal-slug-super-vehicle-001.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Super Mario Kart',
        platform: 'snes',
        tag: 'mariokart',
        src: 'https://www.retrogames.cc/embed/18635-super-mario-kart-usa-hack-by-ok-impala-v1-0-super-mario-kart-the-impala-battles-custom-battle-tracks.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Gran Turismo 2',
        platform: 'psx',
        tag: 'gran2',
        src: 'https://static.arcadespot.com/retroemulator.php?system=ps1&game=2018/01/gran-turismo-2.pbp',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Tekken 3',
        platform: 'psx',
        tag: 'tk3',
        src: 'https://www.retrogames.cc/embed/40238-tekken-3.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Bloody Roar 2',
        platform: 'psx',
        tag: 'blr2',
        src: 'https://www.retrogames.cc/embed/41623-bloody-roar-2-bringer-of-new-age.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Captain Tsubasa',
        platform: 'psx',
        tag: 'tsubasa',
        src: 'https://www.retrogames.cc/embed/41646-captain-tsubasa-j-get-in-the-tomorrow.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Carmageddon',
        platform: 'psx',
        tag: 'carma',
        src: 'https://www.retrogames.cc/embed/41647-carmageddon.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'McRae Rally 2',
        platform: 'psx',
        tag: 'colin2',
        src: 'https://www.retrogames.cc/embed/41669-colin-mcrae-rally-2.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Street Fighter',
        platform: 'Arcade',
        tag: 'stf',
        src: 'https://www.retrogames.cc/embed/10042-street-fighter-ii-champion-edition-yyc-bootleg-set-2-920313-etc-bootleg.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Bushido Blade 2',
        platform: 'psx',
        tag: 'bu2',
        src: 'https://www.retrogames.cc/embed/41635-bushido-blade-2.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Crash Bandicoot',
        platform: 'psx',
        tag: 'crash',
        src: 'https://www.retrogames.cc/embed/40784-crash-bandicoot.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Rampage 2 - Universal Tour (USA)'),
        platform: 'Nintendo 64',
        tag: 'ramp2',
        src: 'https://www.retrogames.cc/embed/32798-rampage-2-universal-tour-usa.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Crash Bandicoot - Warped'),
        platform: 'psx',
        tag: 'crashwar',
        src: 'https://www.retrogames.cc/embed/40136-crash-bandicoot-warped.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Crash Bandicoot 2 - Cortex Strikes Back'),
        platform: 'psx',
        tag: 'crash2',
        src: 'https://www.retrogames.cc/embed/40129-crash-bandicoot-2-cortex-strikes-back.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Dead or Alive',
        platform: 'psx',
        tag: 'dora',
        src: 'https://www.retrogames.cc/embed/41717-dead-or-alive.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Crisis Beat',
        platform: 'psx',
        tag: 'crib',
        src: 'https://www.retrogames.cc/embed/41694-crisis-beat.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Destruction Derby',
        platform: 'psx',
        tag: 'dd',
        src: 'https://www.retrogames.cc/embed/41725-destruction-derby.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Destruction Derby 2',
        platform: 'psx',
        tag: 'dd2',
        src: 'https://www.retrogames.cc/embed/41726-destruction-derby-2.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Destruction Derby Raw',
        platform: 'psx',
        tag: 'ddraw',
        src: 'https://www.retrogames.cc/embed/41727-destruction-derby-raw.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: 'Doom',
        platform: 'psx',
        tag: 'doom',
        src: 'https://www.retrogames.cc/embed/41739-doom.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Dragon Ball GT - Final Bout'),
        platform: 'psx',
        tag: 'dragongt',
        src: 'https://www.retrogames.cc/embed/40092-dragon-ball-gt-final-bout.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Dragon Ball Z: The Legend'),
        platform: 'psx',
        tag: 'dragonle',
        src: 'https://www.retrogames.cc/embed/40793-dragon-ball-z-the-legend.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Dragon Ball Z: The Legend'),
        platform: 'psx',
        tag: 'dragonle',
        src: 'https://www.retrogames.cc/embed/40793-dragon-ball-z-the-legend.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Dragon Ball Z: Ultimate Battle 22'),
        platform: 'psx',
        tag: 'dragonult',
        src: 'https://www.retrogames.cc/embed/40794-dragon-ball-z-ultimate-battle-22.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Driver 2: Back on the Streets'),
        platform: 'psx',
        tag: 'driver2',
        src: 'https://www.retrogames.cc/embed/41742-driver-2-back-on-the-streets.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Grand Theft Auto 2'),
        platform: 'psx',
        tag: 'gta2',
        src: 'https://www.retrogames.cc/embed/41828-grand-theft-auto-2.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('OutRunners (World)'),
        platform: 'arcade',
        tag: 'outw',
        src: 'https://www.retrogames.cc/embed/42461-outrunners-world.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Cruis`n USA'),
        platform: 'N64',
        tag: 'cruUSA',
        src: 'https://www.retrogames.cc/embed/32646-cruis-n-usa-usa-rev-b.html',
        gameWidth: 600,
        gameHeight: 450,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('Oddworld: Abe’s Oddysee'),
        platform: 'psx',
        tag: 'abe',
        src: 'https://www.retrogames.onl/psx/abyss-odyssey.html',
        gameWidth: 650,
        gameHeight: 550,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    },
    {
        id: idPlusPlus(),
        title: gameNameCutter('slither.io'),
        platform: 'web',
        tag: 'slit',
        src: 'https://slither.io',
        gameWidth: 650,
        gameHeight: 550,
        frameBorder: 0,
        allowFullScreen: 'true',
        buttonColor: '#ff0000',
        textColor: textColor,
        svgWidth: svgWidth,
        svgHeight: svgHeight,
    }








];

let tagGameSelected = '';

export const getCurrentGameTag = function (){
    return tagGameSelected;
}

export const setCurrentGameTag = function (tag){
    tagGameSelected = tag;
}

export const getGameList = function (){
    return gameList;
}

export const getRandomGame = function (){
    const listSize = gameList.length;
    // get a number between zero and listSize
    const randNumber = Math.floor(Math.random() * (listSize + 1));
    return gameList[randNumber];
}

export const getGameByTag = function (tag){
    return gameList.find((item) => item.tag === tag);
}

